services:
  model:
    build: ./model
    volumes:
      - ./model/src:/app/src
    working_dir: /app
    command:
      [
        "jupyter",
        "notebook",
        "--ip=0.0.0.0",
        "--port=8888",
        "--allow-root",
        "--NotebookApp.token=''",
        "--NotebookApp.password=''",
      ]
    ports:
      - "8888:8888"

  web:
    build: ./web
    ports:
      - "7860:7860"
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
