version: "3.9"

services:
  model:
    build: ./model
    volumes:
      - ./model/src:/app/src
    working_dir: /app
    command:
      [
        "jupyter",
        "notebook",
        "--ip=0.0.0.0",
        "--port=8888",
        "--allow-root",
        "--NotebookApp.token=''",
        "--NotebookApp.password=''",
      ]
    ports:
      - "8888:8888"

  web:
    build: ./web
    volumes:
      - ./web/src:/app/src
    working_dir: /app
    command: ["python", "src/app.py"]
    ports:
      - "5000:5000"
    depends_on:
      - model
